# Generated by Django 3.1.2 on 2021-06-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_synonyms_google_spreadsheet_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='search_google_spreadsheet_column',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='search_google_spreadsheet_sheet_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='synonyms_google_spreadsheet_column',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='synonyms_google_spreadsheet_sheet_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='search_google_spreadsheet_key',
            field=models.CharField(blank=True, max_length=1676),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='synonyms_google_spreadsheet_key',
            field=models.CharField(blank=True, max_length=1676),
        ),
    ]
