# Generated by Django 3.1.2 on 2021-07-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210628_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='search_google_spreadsheet_column',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='search_google_spreadsheet_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='search_google_spreadsheet_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='search_google_spreadsheet_key',
            field=models.CharField(blank=True, default='', max_length=1676),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='search_google_spreadsheet_sheet_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='synonyms_google_spreadsheet_column',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='synonyms_google_spreadsheet_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='synonyms_google_spreadsheet_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='synonyms_google_spreadsheet_key',
            field=models.CharField(blank=True, default='', max_length=1676),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='synonyms_google_spreadsheet_sheet_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
